title: <p align="center"> Abs Varkey </p>
logo: /assets/img/Logo1.jpg

description: 
  <p align="center">
  <a href="assets/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/absvarkey/">LinkedIn</a> |
  <a href="https://github.com/abe-twistedtech">GitHub</a> |
  <a href="www.bistra.tech">WebSite</a> |

  <br>
  A seasoned professional in leading transformative initiatives across diverse industries. 
  Proficient in Digital Enterprise and Solutions Architecture delivery, 
  paired with proficiency in Artificial Intelligence/Machine Learning implementation and ESG.
  </br>
  </p>

show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
